version: '3'
services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:5.6'
    restart: 'no'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - '/Users/shuimu/Volumes/mysql:/var/lib/mysql'
